# This workflow runs on every push and checks whether everything looks good

name: Quick check

on:
  push:
    tags:
      - "!v*"
    branches:
      - "*"
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  quick_check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9 # v1.12.0
        with:
          cache: false
          toolchain: nightly
          components: cargo, clippy, rust-docs, rust-src, rustfmt, rustc, rust-std

      - name: Install Rust tooling
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy -- -D warnings

      - name: Cargo nextest
        run: cargo nextest run

      - name: Cargo check
        run: cargo check
